[versions]
accompanistSwiperefresh = "0.36.0"
activityCompose = "1.13.0"
agp = "9.3.1"
apolloRuntime = "3.8.6"
coilCompose = "2.7.0"
glideCompiler = "5.0.9"
composeBom = "2025.08.00"
constraintlayoutCompose = "1.1.2"
coreTestingVersion = "2.2.0"
hiltAndroidCompiler = "2.60.1"
hiltNavigationCompose = "1.4.0"
hiltAndroidGradle = "2.60.1"
kotlin = "2.4.10"
kotlin_coruntines_android = "1.11.0"
coreKtx = "1.19.0"
kotlinSerialization = "2.4.10"
kotlinxSerializationJson = "1.11.0"
landscapistGlide = "2.5.1"
legacySupportV4 = "1.0.0"
lifecycleViewmodelKtx = "2.9.2"
material3Android = "1.3.2"
mockwebserver = "5.4.0"
navigationCompose = "2.9.8"
navigationUiKtx = "2.9.8"
pagingRuntimeKtx = "3.3.6"
powerspinner = "1.2.7"
retrofit = "3.0.0"
android-material = "1.14.0"
androidx-appcompat = "1.7.1"
test-junit = "1.3.0"
junit = "4.13.2"
test-espresso = "3.7.0"
gson = "2.14.0"
retrofit-interceptor = "5.4.0"
uiTooling = "1.11.4"
volley = "1.2.1"
pagingCommonAndroid = "3.3.6"
jetbrainsKotlinJvm = "2.4.10"
androidx-test = "1.7.0"
compose = "1.11.4"
glide = "5.0.9"
#testing
truth = "1.4.5"
turbine = "1.2.1"
corutinesTest = "1.11.0"
mockk = "1.14.11"
androidBuiltInKotlin = "9.3.1"

[libraries]
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }

compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTestingVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "corutinesTest" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coruntines_android" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapistGlide" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
powerspinner = { module = "com.github.skydoves:powerspinner", version.ref = "powerspinner" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "test-espresso" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofit-interceptor" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
androidx-paging-common-android = { group = "androidx.paging", name = "paging-common-android", version.ref = "pagingCommonAndroid" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apolloRuntime" }

##compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingRuntimeKtx" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

#compose navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#compose testing
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }


android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidGradle" }
navigation-safe-gradle = { id = "androidx.navigation.safeargs", version.ref = "navigationUiKtx" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "hiltAndroidGradle" }

[bundles]

compose = [
    "androidx-compose-bom",
    "androidx-runtime",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-material",
    "androidx-material3-android",
    "androidx-constraintlayout-compose",
    "androidx-paging-compose",
    "androidx-ui-tooling-preview",
    "coil-compose",
    "androidx-activity-compose"
]

compose_navigation = [
    "androidx-navigation-compose",
    "androidx-hilt-navigation-compose"
]

compose_testing = [
    "compose-ui-test-junit4",
    "compose-ui-test-manifest"
]
